[package]
name = "ledge_engine"
version = "0.1.0"
authors = ["Daniel Irons <daniel.w.irons@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ledge_engine"
path = "src/lib.rs"

[dependencies]
vulkano = "0.20"
vulkano-shaders = "0.20"
vulkano-win = "0.20"
winit = "0.24"
winit_input_helper = "0.7"
png = "*"
image = "0.23.12"
mopa = "0.2.2"
vector-map = "1.0.1"
rand = "0.8.3"
cgmath = "0.18.0"
renderdoc = "0.10.1"